version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/percept
      MYSQL_ROOT_PASSWORD: q123456
      MYSQL_DATABASE: percept
      MYSQL_USER: root
      MYSQL_PASSWORD: q123456
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
